app/controllers/mock-login.js
app/services/current-session.js
app/templates/mock-login.hbs

Refactoring of mock login controller to new async task . Temporary bypass of login function offered by the mock-login plugin (from the component). A newer version of mock-login is needed.

Login bug fix

---

app/routes/sites/index.js

According to https://binnenland.atlassian.net/browse/CLBV-155

Put primary site first instead of last

---

app/components/sidebar-container.hbs
app/styles/project/_c-sidebar-container.scss
app/templates/core-data.hbs
app/templates/sites.hbs

Hi guys. Can you test the responsiveness this time? On my pc it seems to work fine and i got rid of the previous bugs. Please let me know if you guys encounter any bugs.

Sidebar component fix with new login page

---

app/components/app-header.hbs

[CLBV-136](https://binnenland.atlassian.net/browse/CLBV-136)
Change the anchor text of the Help page. This link should also now redirect to the [Loket FAQ](https://abb-vlaanderen.gitbook.io/handleiding-loket/veelgestelde-vragen).
To test this you can just navigate to whatever page that contains the main header (e.g. /mock-login)
On the top right you can see the `help` link. This will redirect you to the Loket FAQ.

Added help page and changed anchor text

---

app/components/organization-status.hbs
app/templates/core-data/admin-unit/index.hbs

Passed status id to component. Removed bad class.

---

app/styles/_shame.scss
app/templates/sites/index.hbs

CLBV-362, just made the column smaller

Fix width of primary site icon

---

app/components/static-page.hbs
app/templates/legal/accessibilitystatement.hbs
app/templates/legal/cookiestatement.hbs
app/templates/legal/disclaimer.hbs

Fix duplicate footer issue

---

app/routes/sites/index.js

[CLBV-402](https://binnenland.atlassian.net/browse/CLBV-402)
Test this by logging out and then going to `/vestigingen`. Instead of a blank screen you now will be redirected to the login screen.

Redirect user to login page when not authenticated

---

app/components/site/contact-data-card.hbs

[CLBV-431](https://binnenland.atlassian.net/browse/CLBV-431)
Added the tel-format helper to the contact-data-card.

add tel-format helper to contact-data-card

---

app/components/site-type-with-name.hbs
app/controllers/sites/new.js
app/controllers/sites/site/edit.js
app/models/site.js
app/templates/sites/index.hbs
app/templates/sites/new.hbs
app/templates/sites/site/edit.hbs
app/templates/sites/site/index.hbs

CLBV-447
Depends on https://github.com/lblod/app-contactgegevens-loket/pull/19

Added site names

---

app/controllers/core-data/admin-unit/index.js
app/templates/core-data/admin-unit/index.hbs

Added extra IF clause to make sure that a message is shown in case of district without a KBO number.

KBO number warning district.

---

app/templates/sites/site/edit.hbs

remove report back from edit page

---

app/models/central-worship-service.js
app/models/recognized-worship-type.js
app/models/user.js
app/models/worship-administrative-unit.js
app/models/worship-service.js
app/routes/core-data/admin-unit.js
app/routes/core-data/util.js

Now the user can login as a worship and check the data, this doesn't include yet the new fields for worships services such as Soort eredienst' + 'Strekking' + 'Grensoverschrijdend'

Made worships available

---

app/controllers/sites/site/edit.js
app/utils/transform-phone-numbers.js

Solve problem with resetting the data and wrong number saving

---

app/controllers/sites/site/edit.js

Fixed bug where the user couldn't click on annuleer when editing a site

---

app/components/contact-data-edit-card.hbs
app/components/province-select.hbs
app/components/province-select.js

Addressbug

---

app/controllers/sites/site/edit.js
app/utils/empty-string-to-null.js

If there's no primary or secondary contact when editing create it

---

app/controllers/sites/new.js
app/controllers/sites/site/edit.js

CLBV-604
To test go to a random admin unit that was not yet edited, then click on site->edit and then cancel, it should go back without problems

In some cases the secondary contact was destroyed for some reason

---

app/helpers/tel-format.js

Ticket description : https://binnenland.atlassian.net/browse/CLBV-680

fixed bug after saving less numbers then 2

---

app/templates/core-data/admin-unit/index.hbs

https://binnenland.atlassian.net/browse/CLBV-662

commented it on core data page

---

app/components/contact-data-edit-card.hbs
app/templates/sites/new.hbs
app/templates/sites/site/edit.hbs

this was the issue : https://binnenland.atlassian.net/browse/CLBV-696

address search automatic in edit and manual in new

---

app/templates/core-data/admin-unit/index.hbs

https://binnenland.atlassian.net/browse/CLBV-731

fixed alternative name

---

.vscode/settings.json
app/components/address-register-selector.js

https://binnenland.atlassian.net/browse/CLBV-722
The address was just missing and that was needed to fix the other 2 steps are just for to show that address is not available

Fixed address not showing

---

app/components/contact-data-edit-card.hbs
app/validations/site-validation.js

https://binnenland.atlassian.net/browse/CLBV-749

changed the requirement of a primary phone number

---

app/styles/_shame.scss
app/templates/sites/site/index.hbs

https://binnenland.atlassian.net/browse/CLBV-764

removed report back and changed layout

---

app/helpers/tel-format.js

https://binnenland.atlassian.net/browse/CLBV-748

bug fix of 0 after +32

---

app/templates/sites/site/edit.hbs
app/templates/sites/site/index.hbs

Small bug that caught my eye while testing something else.

fix: change label from English to Dutch

---

app/router.js

https://binnenland.atlassian.net/browse/CLBV-765

no mock login in QA

---

app/templates/sites/site/index.hbs

https://binnenland.atlassian.net/browse/CLBV-806

deleted report back

---

app/router.js

https://binnenland.atlassian.net/browse/CLBV-765

bug fix of no mock login in QA

---

app/controllers/sites/site/edit.js
app/controllers/sites/site/index.js
app/models/site.js
app/templates/sites/site/index.hbs

https://binnenland.atlassian.net/browse/CLBV-709

added lastmodifiedbywho

---

.woodpecker/.feature.yml
.woodpecker/.test-build.yml
.woodpecker/.test-pr.yml
package.json
tests/unit/validators/nested-validator-test.js

- run the linter and tests for PRs
- test if the docker image still builds in PRs
- add the "feature" image pipeline which makes it easier to test new changes without having to tag releases

Update the CI setup

---

app/templates/sites/new.hbs
app/templates/sites/site/edit.hbs
app/templates/sites/site/index.hbs

Seems like the header got an incorrect name at some point

replace kerngegevens by algemeen

---

app/components/app-header.hbs
app/controllers/sites/index.js
app/index.html
app/router.js
app/templates/application.hbs
app/templates/contact.hbs
app/templates/core-data.hbs
app/templates/sites/index.hbs
app/templates/sites/site.hbs
app/templates/sites/site/edit.hbs
app/templates/sites/site/index.hbs

This fixes some small issues I came across when testing the app.

Small app improvements

---

app/controllers/sites/new.js
app/controllers/sites/site/edit.js
app/helpers/tel-format.js
app/models/contact-point.js
app/utils/transform-phone-numbers.js
package-lock.json
package.json
tests/unit/helpers/tel-format-test.js

This applies the [improvements from OP](https://github.com/lblod/frontend-organization-portal/pull/677) to our version as well.
Specifically this now respects the area code of Belgian numbers and also attempts to format non Belgian numbers so they are easier to read.
I'm not sure how to tests this manually, the environments I found don't seem to contain any useful phone numbers (or they are hard to find). The unit tests cover a lot of cases though.

[CLBV-1005] Phone number formatting improvements

---

.woodpecker/.feature.yml
.woodpecker/.latest.yml
.woodpecker/.release.yml
.woodpecker/.test-build.yml
.woodpecker/.test-pr.yml

Update Woodpecker CI config files

---

app/templates/sites/index.hbs

[CLBV-980] Disable extra column if edit-feature is on false.

Disable the 'laatste aanpassing' column if edit-feature: false
